name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Run Commands on AWS EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 3.110.185.2
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir yay
